### ISSUE TITLE
Question about strdup usage

### ISSUE THREAD

**Issue by anteloio** [mikim42/Get_next_line#1]
Hi @mikim42, thanks for sharing your solution. 

If you don't mind, could you explain why you'd add `+ len + 1` in line 26 below?
Isn't `strdup` expecting a string as parameter? What's the effect of adding an integer value to it?

https://github.com/mikim42/get_next_line/blob/c1ee21a2d0ca2c05be772d0161d6dbaff42cb3ff/get_next_line.c#L26

Thanks!

**Comment by mikim42** [comment]
Hello,

s[fd][len] is similar to s[fd] + len.
First one is using index operator to access certain index, and second one is just increasing the value of the address to get the pointer to the certain index.

So, in the line, s[fd][len] is where '\n' is. And, I want to duplicate the string with the newline so that +1 increases the pointer and duplicates without the newline.

**Comment by anteloio** [comment]
Wow! I get it now!! 

Thanks a lot for the quick reply and clear explanation :)
